// Golden v1 vaults: the app's crypto code must open each committed fixture
// exactly. If this fails, existing vaults would no longer open. Fix the code,
// never the fixtures (see fixtures/*/README.md).
//
// vault-v1       generated by scripts/generate-golden-vault.mts
// vault-v1-real  exported from a release build of the app

import { readFileSync } from 'node:fs'
import { beforeAll, describe, expect, it } from 'vitest'
import { decrypt, decryptLensMasterKey, decryptMasterKey } from './crypto'

type PersistedItem = { id: string; label: string; type: string; encryptedValue: string }
type PersistedLens = {
  id: string
  name: string
  createdAt: string
  itemCount: number
  encryptedMasterKey: string
  items: PersistedItem[]
  deletedAt?: string
}
type ExpectedLenses = Record<string, { name: string; items: Record<string, string> }>

const XCHACHA_NONCE = 24
const TAG = 16

const bytes = (b64: string) => new Uint8Array(Buffer.from(b64, 'base64'))
const b64 = (data: Uint8Array) => Buffer.from(data).toString('base64')
const flipByte = (blob: string, index: number) => {
  const data = bytes(blob)
  data[index] ^= 0x01
  return b64(data)
}

describe.each(['vault-v1', 'vault-v1-real'])('golden fixture %s', (fixtureDir) => {
  const fixture = (name: string) =>
    JSON.parse(readFileSync(new URL(`../../fixtures/${fixtureDir}/${name}`, import.meta.url), 'utf8'))

  const vault: Record<string, string> = fixture('vault.json')
  const expected: { password: string; lenses: ExpectedLenses; recycleBin: ExpectedLenses } =
    fixture('expected.json')
  const lenses: PersistedLens[] = JSON.parse(vault['still-lenses'])
  const recycleBin: PersistedLens[] = JSON.parse(vault['still-recycle-bin'])
  const allLenses = [...lenses, ...recycleBin]
  const allExpected = { ...expected.lenses, ...expected.recycleBin }

  let appKey: Uint8Array

  beforeAll(async () => {
    appKey = await decryptMasterKey(
      vault['still-encrypted-master-key'],
      expected.password,
      vault['still-salt'],
    )
  })

  describe('contents', () => {
    it('stores exactly the five localStorage keys', () => {
      expect(Object.keys(vault).sort()).toEqual([
        'still-encrypted-master-key',
        'still-has-pin',
        'still-lenses',
        'still-recycle-bin',
        'still-salt',
      ])
      expect(vault['still-has-pin']).toBe('false')
    })

    it('unlocks the 32-byte app master key with the password', () => {
      expect(appKey).toBeInstanceOf(Uint8Array)
      expect(appKey.length).toBe(32)
    })

    for (const [listName, list, expectedList] of [
      ['lenses', lenses, expected.lenses],
      ['recycle bin', recycleBin, expected.recycleBin],
    ] as const) {
      it(`decrypts every item in the ${listName} to its exact plaintext`, async () => {
        expect(list.map((lens) => lens.id).sort()).toEqual(Object.keys(expectedList).sort())

        for (const lens of list) {
          const want = expectedList[lens.id]
          expect(lens.name).toBe(want.name)
          expect(lens.itemCount).toBe(lens.items.length)
          expect(lens.items.map((item) => item.id).sort()).toEqual(Object.keys(want.items).sort())

          const lensKey = await decryptLensMasterKey(lens.encryptedMasterKey, appKey)
          expect(lensKey.length).toBe(32)
          for (const item of lens.items) {
            expect(await decrypt(item.encryptedValue, lensKey)).toBe(want.items[item.id])
          }
        }
      })
    }
  })

  describe('byte layout', () => {
    it('uses canonical standard base64 with padding', () => {
      const blobs = [
        vault['still-encrypted-master-key'],
        vault['still-salt'],
        ...allLenses.map((lens) => lens.encryptedMasterKey),
        ...allLenses.flatMap((lens) => lens.items.map((item) => item.encryptedValue)),
      ]
      for (const blob of blobs) {
        expect(blob).toMatch(/^[A-Za-z0-9+/]+={0,2}$/)
        expect(b64(bytes(blob))).toBe(blob)
      }
    })

    it('has a 16-byte salt', () => {
      expect(bytes(vault['still-salt']).length).toBe(16)
    })

    it('stores the master key as version 1 + nonce + 32-byte key + tag (73 bytes)', () => {
      const blob = bytes(vault['still-encrypted-master-key'])
      expect(blob.length).toBe(1 + XCHACHA_NONCE + 32 + TAG)
      expect(blob[0]).toBe(1)
    })

    it('stores each wrapped Lens key as version 1 + nonce + 32-byte key + tag (73 bytes)', () => {
      for (const lens of allLenses) {
        const blob = bytes(lens.encryptedMasterKey)
        expect(blob.length).toBe(1 + XCHACHA_NONCE + 32 + TAG)
        expect(blob[0]).toBe(1)
      }
    })

    it('stores each item as version 1 + LE uint32 subkey id + nonce + ciphertext + tag', () => {
      for (const lens of allLenses) {
        for (const item of lens.items) {
          const blob = bytes(item.encryptedValue)
          const plaintextBytes = Buffer.byteLength(allExpected[lens.id].items[item.id], 'utf8')
          expect(blob.length).toBe(1 + 4 + XCHACHA_NONCE + plaintextBytes + TAG)
          expect(blob[0]).toBe(1)
        }
      }
    })
  })

  describe('rejection', () => {
    it('rejects a wrong password', async () => {
      await expect(
        decryptMasterKey(vault['still-encrypted-master-key'], expected.password.slice(0, -1), vault['still-salt']),
      ).rejects.toThrow()
    })

    it('rejects a master-key blob with a flipped tag byte', async () => {
      const blob = vault['still-encrypted-master-key']
      await expect(
        decryptMasterKey(flipByte(blob, bytes(blob).length - 1), expected.password, vault['still-salt']),
      ).rejects.toThrow()
    })

    it('rejects a wrapped Lens key with a flipped version, nonce or tag byte', async () => {
      for (const lens of allLenses) {
        const blob = lens.encryptedMasterKey
        for (const index of [0, 1, bytes(blob).length - 1]) {
          await expect(decryptLensMasterKey(flipByte(blob, index), appKey)).rejects.toThrow()
        }
      }
    })

    it('rejects an item with a flipped version, subkey id, nonce or ciphertext byte', async () => {
      for (const lens of allLenses) {
        const lensKey = await decryptLensMasterKey(lens.encryptedMasterKey, appKey)
        for (const item of lens.items) {
          const blob = item.encryptedValue
          for (const index of [0, 1, 5, 5 + XCHACHA_NONCE, bytes(blob).length - 1]) {
            await expect(decrypt(flipByte(blob, index), lensKey)).rejects.toThrow()
          }
        }
      }
    })

    it('rejects an item decrypted with another Lens key', async () => {
      const withItems = allLenses.find((lens) => lens.items.length > 0)!
      const other = allLenses.find((lens) => lens.id !== withItems.id)!
      const otherKey = await decryptLensMasterKey(other.encryptedMasterKey, appKey)
      await expect(decrypt(withItems.items[0].encryptedValue, otherKey)).rejects.toThrow()
    })
  })
})
