//! Fixed-input v1 vectors generated by the JS app's libsodium
//! (fixtures/vault-v1/vectors.json). Rust must reproduce every byte: that
//! also proves the JS app can read what Rust writes.

mod common;

use common::{array, fixture, hex};
use still_core::crypto::{
    decrypt_item, decrypt_lens_key, decrypt_master_key, derive_key_from_password, derive_subkey,
    encrypt_item_with, wrap_key_with_nonce,
};
use still_core::Key;

#[test]
fn argon2id_outputs_match() {
    let v = fixture("vault-v1/vectors.json");
    assert_eq!(v["argon2"]["params"]["opslimit"], 4);
    assert_eq!(v["argon2"]["params"]["memlimit"], 1_073_741_824u64);
    for vector in v["argon2"]["vectors"].as_array().unwrap() {
        let password = vector["password"].as_str().unwrap();
        assert_eq!(hex(&vector["passwordUtf8"]), password.as_bytes());
        let key = derive_key_from_password(password, &array(&vector["salt"])).unwrap();
        assert_eq!(key.expose().to_vec(), hex(&vector["key"]), "{password:?}");
    }
}

#[test]
fn master_key_blob_matches_and_opens() {
    let v = fixture("vault-v1/vectors.json");
    let m = &v["masterKeyBlob"];
    let password_key = Key::from_bytes(array(&v["argon2"]["vectors"][1]["key"]));
    let master_key = Key::from_bytes(array(&m["masterKey"]));
    assert_eq!(
        wrap_key_with_nonce(&master_key, &password_key, array(&m["nonce"])),
        m["blob"].as_str().unwrap()
    );

    let opened = decrypt_master_key(
        m["blob"].as_str().unwrap(),
        m["password"].as_str().unwrap(),
        m["salt"].as_str().unwrap(),
    );
    assert_eq!(opened.unwrap().expose(), master_key.expose());
}

#[test]
fn lens_key_blob_matches_and_opens() {
    let v = fixture("vault-v1/vectors.json");
    let l = &v["lensKeyBlob"];
    let app_key = Key::from_bytes(array(&l["appMasterKey"]));
    let lens_key = Key::from_bytes(array(&l["lensKey"]));
    assert_eq!(
        wrap_key_with_nonce(&lens_key, &app_key, array(&l["nonce"])),
        l["blob"].as_str().unwrap()
    );
    assert_eq!(
        decrypt_lens_key(l["blob"].as_str().unwrap(), &app_key)
            .unwrap()
            .expose(),
        lens_key.expose()
    );
}

#[test]
fn kdf_subkeys_match() {
    let v = fixture("vault-v1/vectors.json");
    assert_eq!(v["kdfContext"], "StillSec");
    let lens_key = Key::from_bytes(array(&v["kdf"]["lensKey"]));
    for vector in v["kdf"]["vectors"].as_array().unwrap() {
        let id = u32::try_from(vector["subkeyId"].as_u64().unwrap()).unwrap();
        assert_eq!(
            derive_subkey(&lens_key, id).expose().to_vec(),
            hex(&vector["subkey"]),
            "subkey id {id}"
        );
    }
}

#[test]
fn item_blobs_match_byte_for_byte_and_open() {
    let v = fixture("vault-v1/vectors.json");
    let lens_key = Key::from_bytes(array(&v["items"]["lensKey"]));
    for vector in v["items"]["vectors"].as_array().unwrap() {
        let plaintext = vector["plaintext"].as_str().unwrap();
        let id = u32::try_from(vector["subkeyId"].as_u64().unwrap()).unwrap();
        let blob = encrypt_item_with(plaintext, &lens_key, id, array(&vector["nonce"])).unwrap();
        assert_eq!(blob, vector["blob"].as_str().unwrap(), "subkey id {id}");
        assert_eq!(decrypt_item(&blob, &lens_key).unwrap(), plaintext);
    }
}
