// Generates fixed-input test vectors for the v1 format by calling libsodium
// directly with fixed keys, nonces, salts and subkey ids. Blobs are laid out
// exactly as src/test/reference/crypto.ts lays them out. Any other implementation (the
// Rust port) must reproduce these bytes exactly.
//
// The output is deterministic. Commit it, and never edit it by hand.
//
//   node scripts/generate-crypto-vectors.mts [--force]

import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import sodiumModule from 'libsodium-wrappers-sumo'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const outPath = join(root, 'fixtures', 'vault-v1', 'vectors.json')

if (existsSync(outPath) && !process.argv.includes('--force')) {
  console.error(`${outPath} already exists. Pass --force only if you really mean to replace it.`)
  process.exit(1)
}

const s = (sodiumModule as any).default ?? sodiumModule
await s.ready

const KDF_CONTEXT = 'StillSec'
const VERSION = 1

const seq = (start: number, length: number) => Uint8Array.from({ length }, (_, i) => (start + i) & 0xff)
const hex = (data: Uint8Array) => Buffer.from(data).toString('hex')
const b64 = (data: Uint8Array) => s.to_base64(data, s.base64_variants.ORIGINAL)

// [version][nonce][ciphertext + tag], as in encryptMasterKey / encryptLensMasterKey.
function wrapKey(plaintextKey: Uint8Array, wrappingKey: Uint8Array, nonce: Uint8Array) {
  const ciphertext = s.crypto_aead_xchacha20poly1305_ietf_encrypt(plaintextKey, null, null, nonce, wrappingKey)
  const blob = new Uint8Array(1 + nonce.length + ciphertext.length)
  blob[0] = VERSION
  blob.set(nonce, 1)
  blob.set(ciphertext, 1 + nonce.length)
  return blob
}

// [version][subkey id, uint32 LE][nonce][ciphertext + tag], as in encrypt().
function encryptItem(plaintext: string, lensKey: Uint8Array, subkeyId: number, nonce: Uint8Array) {
  const subkey = s.crypto_kdf_derive_from_key(32, BigInt(subkeyId), KDF_CONTEXT, lensKey)
  const ciphertext = s.crypto_aead_xchacha20poly1305_ietf_encrypt(s.from_string(plaintext), null, null, nonce, subkey)
  const blob = new Uint8Array(1 + 4 + nonce.length + ciphertext.length)
  blob[0] = VERSION
  new DataView(blob.buffer).setUint32(1, subkeyId, true)
  blob.set(nonce, 5)
  blob.set(ciphertext, 5 + nonce.length)
  return blob
}

const NONCE = s.crypto_aead_xchacha20poly1305_ietf_NPUBBYTES
const argon2 = {
  algorithm: 'argon2id13',
  opslimit: s.crypto_pwhash_OPSLIMIT_SENSITIVE,
  memlimit: s.crypto_pwhash_MEMLIMIT_SENSITIVE,
  outputBytes: 32,
}
const derive = (password: string, salt: Uint8Array) =>
  s.crypto_pwhash(32, password, salt, argon2.opslimit, argon2.memlimit, s.crypto_pwhash_ALG_ARGON2ID13)

// Argon2id: password → 32-byte key.
const argon2Vectors = [
  { password: 'password', salt: seq(0x00, 16) },
  { password: 'Stíll-golden-v1 🔑 horse', salt: seq(0x10, 16) },
].map(({ password, salt }) => ({
  password,
  passwordUtf8: hex(s.from_string(password)),
  salt: hex(salt),
  key: hex(derive(password, salt)),
}))

// Master-key blob: the app master key wrapped with the Argon2id output.
const masterKey = seq(0x60, 32)
const masterNonce = seq(0x80, NONCE)
const masterWrappingKey = Buffer.from(argon2Vectors[1].key, 'hex')
const masterKeyBlob = {
  password: argon2Vectors[1].password,
  salt: b64(Buffer.from(argon2Vectors[1].salt, 'hex')),
  nonce: hex(masterNonce),
  masterKey: hex(masterKey),
  blob: b64(wrapKey(masterKey, masterWrappingKey, masterNonce)),
}

// Wrapped Lens-key blob: the raw app master key wraps a Lens key directly.
const lensKey = seq(0x40, 32)
const lensNonce = seq(0xa0, NONCE)
const lensKeyBlob = {
  appMasterKey: hex(masterKey),
  nonce: hex(lensNonce),
  lensKey: hex(lensKey),
  blob: b64(wrapKey(lensKey, masterKey, lensNonce)),
}

// crypto_kdf_derive_from_key(32, id, "StillSec", lensKey).
const kdfVectors = [0, 1, 0x12345678, 0xffffffff].map((subkeyId) => ({
  subkeyId,
  subkey: hex(s.crypto_kdf_derive_from_key(32, BigInt(subkeyId), KDF_CONTEXT, lensKey)),
}))

// Item blobs.
const itemVectors = [
  { plaintext: 'sk-test-0123456789abcdef', subkeyId: 0 },
  { plaintext: 'hunter2-Ünïcødé-密码-🔐', subkeyId: 1 },
  { plaintext: '  spaced out  \n', subkeyId: 0x12345678 },
  { plaintext: 'x'.repeat(4096), subkeyId: 0xffffffff },
].map(({ plaintext, subkeyId }, i) => {
  const nonce = seq(0xc0 + i, NONCE)
  return {
    plaintext,
    subkeyId,
    nonce: hex(nonce),
    blob: b64(encryptItem(plaintext, lensKey, subkeyId, nonce)),
  }
})

const vectors = {
  comment:
    'Fixed-input v1 vectors. Raw bytes are hex; blobs are base64 (standard, padded) exactly as stored. ' +
    'Generated by scripts/generate-crypto-vectors.mts. Do not edit.',
  generatedWith: {
    package: `libsodium-wrappers-sumo@${
      JSON.parse(readFileSync(join(root, 'node_modules', 'libsodium-wrappers-sumo', 'package.json'), 'utf8')).version
    }`,
    libsodium: s.sodium_version_string(),
  },
  kdfContext: KDF_CONTEXT,
  argon2: { params: argon2, vectors: argon2Vectors },
  masterKeyBlob,
  lensKeyBlob,
  kdf: { lensKey: hex(lensKey), vectors: kdfVectors },
  items: { lensKey: hex(lensKey), vectors: itemVectors },
}

writeFileSync(outPath, JSON.stringify(vectors, null, 2) + '\n')
console.log(`Wrote ${outPath}`)
